validators/iban.py
With the current implementation the regex didn't match for belgian and norwegian ibans. These are only 15 or 16 characters long (https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country).
=> Fixed validation for norwegian and belgian ibans

tests/test_url.py, validators/url.py
This PR addresses issue #25.
Modified url validator to allow private and local IP addresses by default.
If required to ensure and validate that an address is public, the flag `public` in the `url` function should be set to true (`public=True`). This will raise a `ValidationFailure` if the IP is private/local.
Also included some unit tests to test the new functionality.
=> Correctly validate private IP addresses by default

tests/test_url.py, validators/url.py
Simple of handling of URLs with a query string and no path, such as `https://www.example.com?bar=baz`. Previously such URLs were flagged as invalid.
=> Handle query strings in URLs without a path

tests/test_ipv4.py, tests/test_ipv6.py, validators/ip_address.py
Fixes #58 
- Added tests to make sure valid IPv4 addresses return False on IPv6 and vice versa
- Made sure any address that lacks a : character returns False on IPv6.
=> Fix IPv4 formatted IP address returning True on ipv6

tests/test_domain.py, validators/domain.py
- Updated regex to not allow numeric only TLDs (examples in tests)
- Allow for idna encoded domains and test for them (examples in tests)
Fixes #47
Fixes #123
=> Fix domain validation

docs/index.rst, tests/test_btc_address.py, validators/__init__.py, validators/btc_address.py
Hello. Please tell me what I did wrong?
Why doesn't travic-ci check?
=> Added validator btc addresses on format P2PKH

.github/workflow/main.yml
Github actions provide a lot of flexibility in terms of CI, we could possible move to Actions instead of travis
=> move from travis to github actions

tests/test_uuid.py, validators/uuid.py
Right now, passing a type to `uuid` that cannot be pattern matched results in `TypeError: expected string or bytes-like object`.
This fixes that by catching any potential `TypeError` and returning `False` in those cases.
=> Validate non-string UUID types

setup.py, tests/test_validation_failure.py, validators/domain.py, validators/truthy.py, validators/utils.py
As python 3.4 is required there's not need to keep six for Python 2
compat.
=> validators: drop six usage

tests/test_ipv4.py, validators/ip_address.py
=> added ipv4 digit lengts validation

.github/workflows/main.yml, poetry.lock, pyproject.toml, validators/utils.py
- adds type hints in utils.py, makes it more pythonic
- decorator package is no longer required
- adds bandit for SAST, updates dependencies
- migrates github action to python w/ poetry and latest versions
=> feat: type hints in utils.py, gh-actions

tests/test_between.py, validators/_extremes.py, validators/between.py, validators/length.py, validators/utils.py
- prefer type inference over explicit typing for function returns
- removes unsettling code in comments from `between.py`
- uses `local` instead of `project` to refer local imports
=> maint: improve type annotations

tests/test_btc_address.py, validators/btc_address.py
- adds required type annotations
- update code formatting and docstring
- tiny refactoring within `btc_address` module
- similar changes in the associated unit-test
=> maint: refresh `btc_address` module

validators/_extremes.py, validators/between.py, validators/btc_address.py, validators/length.py, validators/utils.py
=> feat: formats google pydoc style for mkdocstring

tests/test_domain.py, validators/domain.py
maint: improves `domain` module
- Uses type hints, improve docs
- Regards [RFC 1034](https://www.rfc-editor.org/rfc/rfc1034) and [RFC 2782](https://www.rfc-editor.org/rfc/rfc2782)
- Updates corresponding test functions
*Issues*
- Closes #52
- Closes #74
- Closes #81
- Closes #89
- Closes #95
- Closes #120
- Closes #124
- Closes #141
- Closes #143
- Closes #199
- Closes #204
*PRs*
- Closes #114
- Closes #179
=> maint: improves `domain` module

validators/__init__.py, validators/btc_address.py, validators/card.py, validators/utils.py
- removes internal module `_extremes.py` from `__init__.py`
- moves segwit pattern compilation to func
- makes card's `value` parameter positional-only
- uses `functools.wraps` to preserve wrapped func signature
> This PR will be open for review, for just 1 hour, from creation, as these changes very small.
=> maint: minor improvements

tests/test_email.py, validators/email.py
- Uses type hints, improve relevant docs
- `email` now has coupling with `domain` module
- moves `whitelist` parameter for future enhancements
- Regards [RFC 1034](https://www.rfc-editor.org/rfc/rfc1034), [RFC 5321](https://www.rfc-editor.org/rfc/rfc5321) and [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322)
- Updates corresponding tests
*Issues*
- Closes #22
- Closes #64
- Closes #115
- Closes #153
- Closes #197
*PRs*
- Closes #134
=> maint: improves `email` module

.github/workflows/main.yml, .pre-commit-config.yaml, docs/index.md, mkdocs.yml, poetry.lock, pyproject.toml
- new doc dependencies: `mkdocs`, `mkdocs-material` and `mkdocstrings`
- auto reference documentation using `mkdocstrings`
- moves `pytest` to "tests" dependency group
- install only pytest for testing in github-ci
- adds pre-commit-hooks (thanks to @jdvala)
*Issues*
- Closes #169
*PRs*
- Closes #173
> This PR will be open for review, for just 1 hour, from creation, as these are small changes.
=> feat: auto docs using mkdocstrings

docs/index.md, tests/test_hostname.py, validators/__init__.py, validators/hostname.py
- hostname can be
- a simple alpha-numeral, in the context of system names
- an ip address, in the context of URLs
- a domain name, in the context of URLs
- in all the above cases, it can be with or without port number
- adds tests, update docs
*PRs*
- Closes #220
=> feat: adds `hostname` validator

validators/domain.py, validators/email.py, validators/ip_address.py, validators/uuid.py
- email's domain part is now compliant to [RFC 5321](https://www.rfc-editor.org/rfc/rfc5321)
- it can also accept simple hostname (like `localhost`)
- fix missing `utf-8` comments
*Issues*
- Closes #108
- Closes #142
=> maint: update `email` module

validators/hostname.py
- Moves port validator to its own function
*Issues*
- Closes #185
=> maint: simplified `hostname` module

validators/domain.py, validators/email.py, validators/hostname.py
- in `domain`: decode value to `utf-8` instead of `ascii`; use `re.match` directly
- in `email`: split `ip_address` to `ipv4` and `ipv6` parameters
- in `hostname`: split `skip_ip_addr` to skip `ipv4` & `ipv6` parameters
=> maint: improve `domain`, `email` & `hostname`

docs/index.md, tests/test_url.py, validators/url.py
- `url` is now coupled with `hostname` module
- adds documentation
- shifts from pure regex to a combination validation
- adds parameters with sane defaults
- `http://-.~_!$&'()*+,;=:%40:80%2f::::::@example.com` will be taken care of in subsequent fixes
*Issues*
- Closes #27
- Closes #41
- Closes #49
- Closes #55
- Closes #63
- Closes #65
- Closes #69
- Closes #78
- Closes #80
- Closes #84
- Closes #87
- Closes #102
- Closes #105
- Closes #116
- Closes #135
- Closes #155
- Closes #178
- Closes #180
- Closes #187
- Closes #188
- Closes #189
- Closes #202
- Closes #206
- Closes #208
- Closes #213
- Closes #217
- Closes #219
*PRs*
- Closes #79
- Closes #91
- Closes #211
- Closes #214
- Closes #243
=> maint: improves `url` module

.github/workflows/pages.yml, docs/gen_docs.py, docs/index.md, mkdocs.yml
=> fix: generate dynamic reference docs

.github/workflows/main.yml, .github/workflows/pages.yml, docs/gen_docs.py, poetry.lock, pyproject.toml, setup.cfg, tests/__init__.py, validators/__init__.py
- moves `pre-commit` to `hooks` group
- uses `isort` to add grouping comments, instead of ignoring them
- `__init__.py` is ignored by `isort` for documentation
- fix missing `-*- coding: utf-8 -*-` annotations
- update `tox` configuration in `pyproject.toml`
- in GitHub actions, `main.yml`:
- changed CI job name to `PreflightChecks`
- updated poetry version to `1.4.1`
- runs `tox` with strategy-matrix
- in `pages.yml`:
- updated poetry version to `1.4.1`
- fix typos
- makes flake8 ignore `.venv`
=> maint: misc changes to dev and ci

pyproject.toml, setup.cfg, tests/i18n/__init__.py, tests/i18n/test_es.py, tests/i18n/test_fi.py, validators/__init__.py, validators/i18n/__init__.py, validators/i18n/es.py, validators/i18n/fi.py
- re-formats `es` and `fi` modules in `i18n`
- uses type hints, updates related tests
- uses google's docstring style
- thanks @tvuotila for the update on finnish ssn
- `i18n` is no longer ignored from linting, formatting or type checking
*Issues*
- Closes #216
*PRs*
- Closes #218
=> maint: improves `i18n` package

README.md, docs/index.md, mkdocs.yml, poetry.lock, pyproject.toml, tests/test_between.py, tests/test_length.py, validators/between.py, validators/utils.py
- `validator` decorator catches `Exception`
- it returns `ValidationFailure` with `reason` when exception happens
- `between` and `length` follow the same pattern as every other module
- adds `py.typed`, includes it in `poetry build`
- updates a few dependencies
- fix link to documentation
*Issues*
- Closes #250
=> feat: @validator now catches `Exception`

.github/workflows/build.yml, build.py, docs/gen_docs.py, pyproject.toml
- adds GitHub workflow to build for PyPI
- adds a convenience script to build package
- `isort`'s first-party is now annotated as `local`
- minor modifications made to `docs/gen_docs.py`
=> feat: add build for pypi workflow

.github/workflows/build.yml, .gitignore, build_pkg.py, docs/gen_docs.py, pyproject.toml
- renames script to `build_pgk.py`
- ignores dynamically generated man pages
- pkg includes `docs/validators.1` in built package
- adds option to select between web and man, Sphinx builds
- updates `build.yml` workflow accordingly
=> fix: improves build process

src/validators/url.py, tests/test_url.py
Attempts to resolve https://github.com/python-validators/validators/issues/288 thanks to @joe733 's recommandation
=> fix: url validator considers urls with /#/ as valid

CHANGES.md
0.21.1 to 0.21.2 contained a breaking change when renaming ValidationFailure to ValidationError
The pr that did this: https://github.com/python-validators/validators/pull/283
And the full changelog: https://github.com/python-validators/validators/compare/0.21.1...0.21.2
This change is not reflected in CHANGES.md which makes it hard for others to see this change.
This PR adds the information to the CHANGES.md file.
=> Add note about ValidationFailure to ValidationError in changes.md

CHANGES.md, SECURITY.md, pyproject.toml, src/validators/__init__.py, src/validators/ip_address.py, tests/test_ip_address.py
=> fix: strict CIDR IP validation; bump version

src/validators/url.py, tests/test_url.py
- Adds `strict_query` (default value is `True`) flag to url validation, 
functional urls with weird query parts should now pass with `strict_query=False`
- The fragment part of an url can now contain `/`
- Added a few tests
*Issues*
- Fixes #296 
Thanks to @joe733 for the proposed changes!
=> fix: Valid URLs failing validation - query and fragment parts

src/validators/__init__.py, src/validators/i18n/__init__.py, src/validators/i18n/fr.py, tests/i18n/test_fr.py
Add a new file in the i18n module containing the following validators :
- french department number validator
- french social security number validator
=> feat: add french i18n validation

.github/workflows/docs.yaml.bkp, .github/workflows/pycqa.yaml, .gitignore, CHANGES.md, README.md, docs/index.md, pyproject.toml, src/validators/_extremes.py, src/validators/btc_address.py, src/validators/card.py, src/validators/domain.py, src/validators/email.py, src/validators/hashes.py, src/validators/hostname.py, src/validators/i18n/es.py, src/validators/i18n/fi.py, src/validators/i18n/fr.py, src/validators/iban.py, src/validators/ip_address.py, src/validators/mac_address.py, src/validators/slug.py, src/validators/url.py, src/validators/utils.py, src/validators/uuid.py
=> maint: rectifies changelog

CHANGES.md, src/validators/domain.py, src/validators/url.py, tests/test_domain.py, tests/test_url.py
- `domain` allows trailing underscore under the pretense of rfc 2782
- adds separator based query parsing
- changelog includes what parameters were removed causing incompatibly
_Issues_
- Closes #315
- Closes #327
- Closes #338
=> patch: `domain` & `url` modules

src/validators/domain.py, tests/test_domain.py
=> fix: domain name not confirming to rfc_2782

src/validators/domain.py, src/validators/utils.py
=> fix: `domain` validation is now more consistent across rfcs

CHANGES.md, SECURITY.md, docs/api/hashes.md, docs/api/hashes.rst, src/validators/__init__.py, src/validators/hashes.py, tests/test_hashes.py
=> feat: adds `base58` and `base64` validators

src/validators/uri.py, src/validators/url.py
- Closes: #40
- Closes: #50
- Closes: #68 
- Closes: #195
=> feat: lays foundation for URI validation

src/validators/__init__.py, src/validators/encoding.py, src/validators/hashes.py
Ref: https://github.com/python-validators/validators/issues/313#issuecomment-2033177439
=> patch: moves `base58` and `base64` into `encoding`

src/validators/ip_address.py, tests/test_ip_address.py
=> fix(ip_address): properly handle private is false

CHANGES.md, CONTRIBUTING.md, SECURITY.md, pyproject.toml, src/validators/__init__.py, src/validators/_tld.txt, src/validators/domain.py
=> hotfix: ensure `_tld.txt` is in `sdist` and `bdist`

CHANGES.md, SECURITY.md, docs/api/crypto_addresses.md, docs/api/crypto_addresses.rst, src/validators/__init__.py, src/validators/crypto_addresses/__init__.py, src/validators/crypto_addresses/trx_address.py, tests/crypto_addresses/test_trx_address.py
* A new validator is added for the Tron (TRC20) address
=> feat: add validator for trx addresses

CHANGES.md, SECURITY.md, docs/api/encoding.md, docs/api/encoding.rst, src/validators/__init__.py, src/validators/encoding.py, tests/test_encoding.py
* A new validator for base16 encoding
* A new validator for base32 encoding
=> feat: add validators for base16 and base32 encodings

pdm.lock, pyproject.toml
⚠️ maint: `validators` now `requires-python = ">=3.8.6"` ⚠️
---
> **Reason**: `mkdocstrings[python]` indirectly depends upon `backports-strenum` which `requires-python >= 3.8.6`.
=> chore: update dependencies

src/validators/url.py
=> fix(url): add hashtag to allowed fragment characters

src/validators/url.py
Enhances `validators.url` to allow
- restricting the allowed schemes (e.g. to accept only https, and nothing else)
- relaxing the allowed schemes to also accept less known schemes (e.g. ws, wss, ldap, ...)
----
This backward compatible change let's library users resolve the problematic cases requested/discussed in
- #352
- #388
=> feat: allow custom URL scheme validation

src/validators/uri.py
The use of `lstrip()` here was a bit too aggressive.
For example:
```
In [1]: "mailto:maximilian.moser@tuwien.ac.at".lstrip("mailto:")
Out[1]: 'ximilian.moser@tuwien.ac.at'
```
But:
```
In [2]: "mailto:maximilian.moser@tuwien.ac.at".removeprefix("mailto:")
Out[2]: 'maximilian.moser@tuwien.ac.at'
```
=> fix(uri): replace `lstrip("mailto:")` with manual prefix removal

src/validators/__init__.py, src/validators/i18n/ru.py
Updates:
* Fix: Removed debug print from ru_inn method to clean up output.
* Docs: Updated method description from "Russia INN." to "Russia." for brevity.
* Feat: Added ru_inn to __init__ for direct module-level access.
=> Refactor API: remove print from ru_inn, update description, and expose via __init__

src/validators/__init__.py, src/validators/card.py, tests/test_card.py
This PR introduces validation for Mir cards (Russian payment system) to the validators library.
Key Changes:
* Added mir() validator function with BIN checks (2200-2204)
* Ensures compliance with Luhn algorithm
* Includes length validation (16 digits standard)
* Added unit tests for valid/invalid cases
Why This Matters:
* Mir is a nationally critical payment system (used in Russia and neighboring countries)
* Required for apps processing payments in RUB
* Maintains parity with other card validators (Visa, Mastercard, Unionpay etc.)
=> Add Mir card validation support

src/validators/mac_address.py
Previously, the MAC address validator would accept invalid MAC addresses that mixed different separators, such as `aa:bb-cc-dd:ee:ff`, but a valid MAC address should use consistent separators throughout.
This PR improves the MAC address validator by adding a check to reject MAC addresses that use mixed separators (both `:` and `-` characters).
=> fix: reject MAC addresses with mixed separators
