- docs/index.rst
Forgot to do this, sorry. And thanks for the release!
> include iban in doc

- tests/test_url.py
- validators/url.py
> Fix a false positive urls

- setup.py
> build with pyp2rpm problem

- tests/test_url.py
- validators/url.py
> fix url validator fails for 'localhost'

- validators/url.py
The current implementation also considers ftp://
> Added ftp:// URL in example

- tests/test_url.py
- validators/url.py
> Fix for URLs with invalid characters in userinfo part

- tests/test_domain.py
- validators/domain.py
fixes #73 
fixes #71 
fixes #66
> Small change to domain RE

- tests/i18n/test_fi.py
- validators/i18n/fi.py
This PR fixes a couple of issues in fi-ssn validator that I've run into.
> Improve fi-ssn validator

- validators/utils.py
Rebased #61 against latest master. Intending to fix CI for it.
> Use inspect.getfullargspec() in Python3

- tests/test_domain.py
- validators/domain.py
Fixes: https://github.com/kvesteri/validators/issues/118
> Fixes issue #118 - single character number domain

- tests/test_ipv4_cidr.py
- tests/test_ipv6_cidr.py
- validators/__init__.py
- validators/ip_address.py
Adds validators for CIDR-notated IPv4 and v6 ranges.
Closes #117.
> IPv4 and IPv6 CIDR validators

- validators/domain.py
Catch the AttributeError exception and return False.
> Handle None type in domain.py

- tests/test_email.py
- validators/email.py
This fix the first point of issue #108.
> Local part of the email address should be less or equal than 64 bytes.

- tests/test_card.py
- validators/__init__.py
- validators/card.py
> New feature: bank card validations

- setup.py
See #162, this is the code part.
> Add python_requires='>=3.4' to setup.py

- .github/workflows/main.yml
> Update Python Testing Matrix

- CHANGES.md
- SECURITY.md
- src/validators/__init__.py
- src/validators/hostname.py
- src/validators/ip_address.py
- src/validators/url.py
- tests/test_url.py
> feat: adds `private` parameter to `ip_address`, `hostname` & `url`

- docs/api/i18n.md
- docs/api/i18n.rst
- src/validators/__init__.py
- src/validators/i18n/__init__.py
- src/validators/i18n/ind.py
- tests/i18n/test_ind.py
> co-authored by: @10kartik
_PRs_
- Closes: #215
> feat: adds indian aadhar and pan validator

- docs/api/finance.md
- docs/api/finance.rst
- mkdocs.yaml
- src/validators/__init__.py
- src/validators/finance.py
- tests/test_finance.py
> co-authored by: @rcorbish
_PRs_
- Closes: #210
> feat: adds `finance` validator

- CHANGES.md
- SECURITY.md
- docs/api/hashes.md
- docs/api/hashes.rst
- src/validators/__init__.py
- src/validators/hashes.py
- tests/test_hashes.py
* Adds a new validator for the SH384 hash
> feat: add validator for sha384 hash

- src/validators/domain.py
- tests/test_domain.py
> fix(domain): accept .onion as a valid TLD
